services:
  pg:
    image: docker.io/postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: go-api-server-rest-db
    volumes:
      - ./pg_storage:/var/lib/postgresql/data
